version: 0.2

phases:
  install:
    commands:
      - echo "Install phase (Docker already available)"

  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t myapp .
      - echo "Running Container"
      - docker run myapp
